[General]
loglevel = notify
bypass-system = true

[Rule]
# Chỉ can thiệp vào luồng của Garena/FreeFire
DOMAIN-SUFFIX,garena.com,Proxy
DOMAIN-SUFFIX,freefiremobile.com,Proxy
FINAL,DIRECT

[Script]
# Sử dụng trực tiếp link RAW của bạn, định dạng chuẩn xác không ngắt dòng
azexl_aim_drag = type=http-response,pattern=^https?:\/\/(.*\.garena\.com|.*\.freefiremobile\.com)\/.*,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/yseavlong2010-dotcom/NOXERA/refs/heads/main/AimX.js

[MITM]
# Bật tính năng giải mã để Script hoạt động
enable = true
hostname = *.garena.com, *.freefiremobile.com
